--- #YAML:1.0
name:               Dancer-Plugin-SporeDefinitionControl
version:            0.07
abstract:           ~
author:
    - Nicolas Oudard <nicolas@oudard.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.3002
    Dancer::Plugin:       0
    Dancer::Plugin::REST:  0.04
    Dancer::Test:         0
    File::Spec:           0
    Test::More:           0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
